#!/bin/bash

# usage: ./mk-all-testpages
# Creates test pages for all known e-reader models and places them
# in the directory "output". If the directory already exists, any
# existing files with conflicting names will be overwritten.


mkdir output 2>/dev/null
cd output

echo 'Creating test documents for all known e-reader models in directory "output"...'

../scripts/mk-welcome 545  565  715  730  generation4
../scripts/mk-welcome 690  720  918  945  paperwhite
../scripts/mk-welcome 777  799  1077 1121 dx
../scripts/mk-welcome 542  567  918  945  fire-1or2
../scripts/mk-welcome 728  767  1149 1201 fire-hd-7inch
../scripts/mk-welcome 1109 1157 1780 1841 fire-hd-8p9inch
../scripts/mk-welcome 520  580  710  770  other

ln -s generation4.pdf generation1.pdf 2>/dev/null
ln -s generation4.pdf generation2.pdf 2>/dev/null
ln -s generation4.pdf touch.pdf 2>/dev/null
ln -s generation4.pdf keyboard.pdf 2>/dev/null
