#!/bin/bash

# This script installs the development ("testing") version of Dontprint
# on a linux machine. This script assumes that your Firefox profile is
# called "default". Run this script with normal privileges (i.e., *not*
# as root)

echo 'Dontprint: Installing Dontprint into the "default" profile of Firefox...'

# cd to the top level directory of the Dontprint source code
cd "`dirname "${BASH_SOURCE[0]}"`"

echo 'Dontprint: Switching to branch "testing"...'
git checkout testing

echo 'Dontprint: Fetching dependencies. This may take some time...'
git submodule init
git submodule update

cd zotero
git submodule init
git submodule update
cd ..

profdir=""
if [ -d "$HOME/.mozilla/firefox" ]; then
  profdir="`echo "$HOME/.mozilla/firefox"/*.default`"
elif [ -d "$HOME/Library/Mozilla/Firefox/Profiles" ]; then
  profdir="`echo "$HOME/Library/Mozilla/Firefox/Profiles"/*.default`"
elif [ -d "$HOME/Library/Application Support/Firefox/Profiles" ]; then
  profdir="`echo "$HOME/Library/Application Support/Firefox/Profiles"/*.default`"
else
  echo "ERROR: Could not find Firefox Profile directory."
  exit 1
fi

if [ ! -d "$profdir" ]; then
  echo "ERROR: Could not find Firefox default profile."
  echo "ERROR: search path was $profdir"
  exit 2
fi

echo
echo 'Dontprint: Registering the addon in the "default" profile of Firefox...'
echo "Dontprint: Profile directory is $profdir"
mkdir "$profdir/extensions" 2>/dev/null
pwd > "$profdir/extensions/dontprint@robamler.github.com"

echo
echo 'Dontprint: Installation completed. Restart Firefox now.'
