#!/bin/bash

# usage: ./build [--dist]
# If the --dist flag is set, then all files that are required for
# the packaged extension will be copied to the directory "dist".

if [ -d zotero-connector ] && ! diff -qr ../dependencies/zotero-connectors/build/chrome zotero-connector > /dev/null ; then
	cat << EOF >&2
ERROR: the directories
    ../dependencies/zotero-connectors/build/chrome
and
    zotero-connector
are different. Building Dontprint for Google Chrome would overwrite the
directory zotero-connector. Make sure to copy all changes in this
directory to
    ../dependencies/zotero-connectors/src/chrome
or
    ../dependencies/zotero-connectors/src/common
before building Dontprint for Google Chrome. To see a list of changes
that would be overwritten, run
    diff -r ../dependencies/zotero-connectors/build/chrome zotero-connector
Once you are confident that the directory zotero-connector does not contain
any important code, remove the directory and run the build script again.
EOF
	exit 1
fi


./package-translators.py

rm -r zotero-connector 2> /dev/null
cd ../dependencies/zotero-connectors/
./build.sh
cd ../../chrome
cp -r ../dependencies/zotero-connectors/build/chrome/ zotero-connector

./mk-manifest.py


if [ "x$1" = "x--dist" ]; then
	if [ -d dist ]; then
		echo 'ERROR: Directory "dist" already exists. Delete the directory and run ./build --dist again.' >&2
		exit 2
	fi

	mkdir dist
	cp -Lr common dontprint-chrome-specifics.js k2pdfopt manifest.json platform-tools translators welcome-detect-demo.png zotero-connector dist
	rm -r dist/zotero-connector/Icon-*.png dist/zotero-connector/images dist/zotero-connector/preferences dist/zotero-connector/itemSelector dist/zotero-connector/manifest.json
fi
