#!/bin/bash

# usage: mk-empty innerWidth innerHeight backgroundColor foregroundColor identifier

echo "<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='$(($1+3))' height='$(($2+4))' version='1.1'>
	<rect width='$(($1+3))' height='$(($2+4))' style='fill:#$3' x='0' y='0' />
	<rect width='2' height='2' style='fill:#$4' x='0' y='0' />
	<rect width='2' height='2' style='fill:#$4' x='0' y='$(($2-2))' />
	<rect width='2' height='2' style='fill:#$4' x='$(($1-2))' y='0' />
	<rect width='2' height='2' style='fill:#$4' x='$(($1-2))' y='$(($2-2))' />
</svg>" | convert svg:- -monochrome $5.png
