#!/bin/bash

#usage: mk-height-measure-page lowHeight heightStripesPerPage pageNum lastPageNum innerWidth identifier

lowHeight=$1
heightStripesPerPage=$2
pageNum=$3
lastPageNum=$4
innerWidth=$5
identifier=$6

innerHeight=$(($1+$2/2))

../../scripts/mk-background $innerWidth $innerHeight ffffff 000000 $identifier-background
../../scripts/mk-height-measure-svg.py $innerWidth $innerHeight $lowHeight $heightStripesPerPage $pageNum $lastPageNum $identifier | rsvg-convert -f pdf -o $identifier.pdf
