#!/bin/bash

#usage: mk-turnpage-w-svg innerWidth innerHeight

echo "<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='$1' height='$2' version='1.1'>
	<rect x='0' y='0' width='$1' height='$2' style='fill:#6e6e6e' />
	<g id='corner'>
		<rect x='0' y='0' width='2' height='2' style='fill:#000000' />
		<rect x='2' y='0' width='2' height='2' style='fill:#ffffff' />
		<rect x='0' y='2' width='2' height='2' style='fill:#ffffff' />
	</g>
	<use xlink:href='#corner' transform='matrix(0,1,-1,0,$1,0)' />
	<use xlink:href='#corner' transform='matrix(0,-1,1,0,0,$2)' />
	<use xlink:href='#corner' transform='matrix(-1,0,0,-1,$1,$2)' />
	
	<g id='arrow' transform='translate($1,0)'>
		<g transform='translate(-522,-1000)'>
			<path style='fill:#000000;stroke:#ffffff;stroke-width:2;stroke-miterlimit:4' d='m 142.61591,1008.036 c -2.77,0 -5,2.23 -5,5 l 0,19.7188 c 0,2.77 2.23,5 5,5 l 331.78854,0 c 0.56649,0 1.08688,-0.1404 1.34032,-0.2108 l 31.42912,-10.1319 c 1.05069,-0.3116 4.60556,-2.2104 4.60556,-4.501 0,-2.2906 -3.55487,-4.2207 -4.60556,-4.5322 l -31.4019,-10.1351 c -0.25747,-0.073 -0.79046,-0.2077 -1.36754,-0.2077 z' />
			<text xml:space='preserve' style='font-size:23px;font-weight:bold;text-align:center;text-anchor:middle;fill:#ffffff;font-family:Linux Biolinum O;' x='307.87817' y='1028.4999'>Turn page to clear the screen...</text>
		</g>
	</g>
	
	<use xlink:href='#arrow' transform='translate(0,$(($2-45)))' />
</svg>"
