#!/bin/bash

#usage: mk-turnpage-w-svg innerWidth innerHeight

echo "<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='$1' height='$2' version='1.1'>
	<rect x='0' y='0' width='$1' height='$2' style='fill:#6e6e6e' />
	<g id='corner'>
		<rect x='0' y='0' width='2' height='2' style='fill:#000000' />
		<rect x='2' y='0' width='2' height='2' style='fill:#ffffff' />
		<rect x='0' y='2' width='2' height='2' style='fill:#ffffff' />
	</g>
	<use xlink:href='#corner' transform='matrix(0,1,-1,0,$1,0)' />
	<use xlink:href='#corner' transform='matrix(0,-1,1,0,0,$2)' />
	<use xlink:href='#corner' transform='matrix(-1,0,0,-1,$1,$2)' />
	
	<g id='turnpage' transform='translate(0,$(($2/2)))'>
		<g transform='matrix(0,-1,1,0,-57.75312,-294.1268)'>
			<rect style='fill:#000000;stroke:#ffffff;stroke-width:2;stroke-miterlimit:4' width='413.55261' height='29.508001' x='-500.90311' y='62.75312' ry='5' rx='5' />
			<text xml:space='preserve' style='font-size:23px;font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;text-align:center;text-anchor:middle;fill:#ffffff;fill-opacity:1;font-family:Linux Biolinum O' x='-294.03427' y='83.216995'>Turn page to clear the screen...</text>
			<path id='arrowhead' style='fill:#ffffff;stroke:none' d='m -469.99545,67.173727 -6.03813,3.361963 -6.03814,-3.361963 6.03814,19.478813 z' />
			<use xlink:href='#arrowhead' transform='translate(363.81355,0)' />
		</g>
	</g>
	
	<use xlink:href='#turnpage' transform='translate($(($1-40)),0)' />
</svg>"
