#!/bin/bash

#usage: mk-width-measure-page lowWidth widthStripesPerPage pageNum lastPageNum innerHeight identifier

lowWidth=$1
widthStripesPerPage=$2
pageNum=$3
lastPageNum=$4
innerHeight=$5
identifier=$6

innerWidth=$(($1+$2/2))

../../scripts/mk-background $innerWidth $innerHeight ffffff 000000 $identifier-background
../../scripts/mk-width-measure-svg.py $innerWidth $innerHeight $lowWidth $widthStripesPerPage $pageNum $lastPageNum $identifier | rsvg-convert -f pdf -o $identifier.pdf
