#!/bin/bash

# This script installs Dontprint from source on a linux or mac machine.
# It assumes that your Firefox profile is called "default". Run this
# script with normal privileges (i.e., NOT as root)
#
# WARNING: The current source code in the git repository can be unstable
# at any time. It is not recommended to use installations from source
# in a production environment. Consider instead downloading a packaged
# version from http://dontprint.net.
#
# IMPORTANT: Uninstall any packaged versions of Dontprint and restart
# Firefox before you run this script!


echo 'Dontprint: Installing Dontprint into the "default" profile of Firefox...'

# cd to the top level directory of the Dontprint source code
cd "`dirname "${BASH_SOURCE[0]}"`"

echo 'Dontprint: Fetching dependencies. This may take some time...'
git submodule init
git submodule update

cd zotero
git submodule init
git submodule update
cd ..

profdir=""
if [ -d "$HOME/.mozilla/firefox" ]; then
  profdir="`echo "$HOME/.mozilla/firefox"/*.default`"
elif [ -d "$HOME/Library/Mozilla/Firefox/Profiles" ]; then
  profdir="`echo "$HOME/Library/Mozilla/Firefox/Profiles"/*.default`"
elif [ -d "$HOME/Library/Application Support/Firefox/Profiles" ]; then
  profdir="`echo "$HOME/Library/Application Support/Firefox/Profiles"/*.default`"
else
  echo "ERROR: Could not find Firefox Profile directory."
  exit 1
fi

if [ ! -d "$profdir" ]; then
  echo "ERROR: Could not find Firefox default profile."
  echo "ERROR: search path was $profdir"
  exit 2
fi

echo
echo 'Dontprint: Registering the addon in the "default" profile of Firefox...'
echo "Dontprint: Profile directory is $profdir"
mkdir "$profdir/extensions" 2>/dev/null
pwd > "$profdir/extensions/dontprint@robamler.github.com"

echo
echo 'Dontprint: Installation completed. Restart Firefox now.'
